# tasks file
---
- name: install
  apt:
    name: "{{ cron_apt_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - cron-apt
    - cron-apt-install

- name: update configuration file
  template:
    src: "{{ cron_apt_etc_cron_apt_conf_file.lstrip('/') }}.j2"
    dest: "{{ cron_apt_etc_cron_apt_conf_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - cron-apt
    - cron-apt-configuration
