# tasks file for cron-apt
---
- name: install
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ cron_apt_dependencies }}"
  tags:
    - configuration
    - cron-apt
    - cron-apt-install

- name: update configuration file
  template:
    src: etc/cron-apt/config.j2
    dest: /etc/cron-apt/config
    owner: root
    group: root
    mode: 0644
  tags:
    - configuration
    - cron-apt
    - cron-apt-configuration
